# Generated by Django 4.2.25 on 2025-10-14 15:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='課程日期')),
                ('name', models.CharField(max_length=200, verbose_name='課程名稱')),
                ('classroom', models.CharField(max_length=50, verbose_name='社課教室')),
            ],
            options={
                'verbose_name': '課程',
                'verbose_name_plural': '課程',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=15, unique=True, verbose_name='學號')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
            ],
            options={
                'verbose_name': '社員',
                'verbose_name_plural': '社員',
            },
        ),
        migrations.CreateModel(
            name='CheckinRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='簽到時間')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.course', verbose_name='課程')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.student', verbose_name='社員')),
            ],
            options={
                'verbose_name': '簽到記錄',
                'verbose_name_plural': '簽到記錄',
                'ordering': ['-checkin_time'],
                'unique_together': {('course', 'student')},
            },
        ),
    ]
