# Generated by Django 4.2.25 on 2025-10-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='member_id',
            field=models.IntegerField(blank=True, help_text='社團內部編號，請使用數字', null=True, unique=True, verbose_name='社員編號'),
        ),
    ]
