# Generated by Django 4.2.25 on 2025-10-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_student_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinrecord',
            name='member_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='社員編號'),
        ),
    ]
